{{ $workerOspRole := .WorkerOspRole }}
{{ range .Sriov }}
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-policy-{{ $workerOspRole }}-{{ .Interface }}
  namespace: openshift-sriov-network-operator
spec:
  deviceType: {{ .DeviceType }}
  mtu: {{ .Mtu }}
  nicSelector:
    pfNames:
    - {{ .Interface }}
  nodeSelector:
    node-role.kubernetes.io/{{ $workerOspRole }}: ""
  numVfs: {{ .NumVfs }}
  priority: 5
  resourceName: sriovnic_{{ .Interface }}
{{ end }}