# permissions for end users to edit computenodeopenstacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: computenodeopenstack-editor-role
rules:
- apiGroups:
  - compute-node.openstack.org
  resources:
  - computenodeopenstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute-node.openstack.org
  resources:
  - computenodeopenstacks/status
  verbs:
  - get
