apiVersion: compute-node.openstack.org/v1alpha1
kind: ComputeNodeOpenStack
metadata:
  name: example-computenodeopenstack
  namespace: openshift-machine-api
spec:
  # Add fields here
  roleName: worker-osp
  clusterName: ostest
  baseWorkerMachineSetName: ostest-worker-0
  k8sServiceIP: 172.30.0.1
  apiIntIP: 192.168.111.5
  workers: 0
  corePinning: "4-7"
  infraDaemonSets:
  - name: multus
    namespace: openshift-multus
  - name: node-exporter
    namespace: openshift-monitoring
  - name: machine-config-daemon
    namespace: openshift-machine-config-operator
  drain:
    drainPodImage: quay.io/openstack-k8s-operators/tripleo-deploy
    enabled: false
  openStackClientAdminSecret: openstackclient-admin
  openStackClientConfigMap: openstackclient
  openStackNamespace: openstack
