apiVersion: compute-node.openstack.org/v1alpha1
kind: ComputeNodeOpenStack
metadata:
  name: example-computenodeopenstack
  namespace: openstack
spec:
  # Add fields here
  roleName: worker-osp
  clusterName: ostest
  baseWorkerMachineSetName: ostest-worker-0
  workers: 0
  dedicated: false
  selinuxDisabled: true
  networkGateway: true
  compute:
    novaComputeCPUDedicatedSet: "4-7"
    novaComputeCPUSharedSet: "0-3"
    sshdPort: 2022
    commonConfigMap: common-config
    ospSecrets: osp-secrets
  network:
    nic: "enp2s0"
    bridgeMappings: "datacentre:br-ex"
    mechanismDrivers: ""
    servicePlugins: ""
    sriov:
    - interface: eno2
      mtu: 9000
      numVfs: 64
      deviceType: vfio-pci
      network: sriov-phy1
    - interface: eno3
      mtu: 9000
      numVfs: 32
      deviceType: netdevice
      network: sriov-phy2
  performance:
    hugepages:
      defaultHugepagesSize: "1G"
      pages:
      - size: "1G"
        count: "16"
# needed if openshift-sdn is not running
#  infraDaemonSets:
#  - name: multus
#    namespace: openshift-multus
#  - name: node-exporter
#    namespace: openshift-monitoring
#  - name: machine-config-daemon
#    namespace: openshift-machine-config-operator
  drain:
    drainPodImage: quay.io/openstack-k8s-operators/tripleo-deploy
    enabled: false
  openStackClientAdminSecret: openstackclient-admin
  openStackClientConfigMap: openstackclient
  serviceAccount: compute-node
