apiVersion: neutron.openstack.org/v1
kind: OVSNodeOsp
metadata:
  name: ovs-node-osp-{{ .WorkerOspRole }}
  namespace: openstack
spec:
  ovsNodeOspImage: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7d6ba1bcc4f403733e44cd2a008dafe1887501f7a3c74084566a4f4d1e46250d
  serviceAccount: neutron-operator
  roleName: {{ .WorkerOspRole }}
  ovnSbRemote: 192.168.25.100 # REMOVE IT, and read it from configmap/secret as in nova operator
  ovsLogLevel: info
  nic: {{ .Nic }}