apiVersion: nova.openstack.org/v1
kind: Virtlogd
metadata:
  name: virtlogd-{{ .WorkerOspRole }}
  namespace: openstack
spec:
  novaLibvirtImage: quay.io/openstack-k8s-operators/nova-libvirt:latest
  roleName: {{ .WorkerOspRole }}
  serviceAccount: nova-operator
