apiVersion: nova.openstack.org/v1beta1
kind: NovaCompute
metadata:
  name: nova-compute-{{ .WorkerOspRole }}
  namespace: openstack
spec:
  novaSecret: {{ .NovaSecret }}
  neutronSecret: {{ .NeutronSecret }}
  placementSecret: {{ .PlacementSecret }}
  transportURLSecret: {{ .TransportURLSecret }}
  novaComputeCpuDedicatedSet: {{ .NovaComputeCPUDedicatedSet }}
  novaComputeCpuSharedSet: {{ .NovaComputeCPUSharedSet }}
  novaComputeImage: docker.io/tripleomaster/centos-binary-nova-compute:current-tripleo
  roleName: {{ .WorkerOspRole }}