apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .ClusterName }}
    machine.openshift.io/cluster-api-machine-role: {{ .WorkerOspRole }}
    machine.openshift.io/cluster-api-machine-type: {{ .WorkerOspRole }}
  name: {{ .ClusterName }}-{{ .WorkerOspRole }}
  namespace: openshift-machine-api
spec:
  replicas: {{ .Workers }}
  deletePolicy: Newest
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .ClusterName }}
      machine.openshift.io/cluster-api-machineset: {{ .ClusterName }}-{{ .WorkerOspRole }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .ClusterName }}
        machine.openshift.io/cluster-api-machine-role: {{ .WorkerOspRole }}
        machine.openshift.io/cluster-api-machine-type: {{ .WorkerOspRole }}
        machine.openshift.io/cluster-api-machineset: {{ .ClusterName }}-{{ .WorkerOspRole }}
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/{{ .WorkerOspRole }}: ""
          network.operator.openshift.io/external-openvswitch: ""
          #beta.kubernetes.io/os: osp # only needed if we want to kick out openshift-sdn
      taints:
      - effect: NoSchedule
        key: dedicated
        value: {{ .WorkerOspRole }}
      providerSpec:
        value:
          hostSelector:
            matchLabels:
              ospRole: {{ .WorkerOspRole }}
          image:
            checksum: {{ .RhcosImageUrl }}.md5sum
            url: {{ .RhcosImageUrl }}
          userData:
            name: {{ .WorkerOspRole }}-user-data
