{{ if not (eq .AvailableNodeCount 0) }}
  {{ $workerOspRole := .WorkerOspRole }}
  {{ $workerOspRoleFormatted := .WorkerOspRole | replace "-" "_" }}
  {{ range $i, $e := .Sriov }}
    {{ if not (eq $i 0) }}
---
    {{ end }}
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: sriov-policy-{{ $workerOspRole }}-{{ $e.Interface }}
  namespace: openshift-sriov-network-operator
  labels:
    compute-node.openstack.org/sriov-policy: "{{ $workerOspRole }}"
spec:
  deviceType: {{ $e.DeviceType }}
  mtu: {{ $e.Mtu }}
  nicSelector:
    {{ if not (eq (len $e.NicSelector.PfNames) 0) }}
    pfNames:
      {{ range $k, $pf := $e.NicSelector.PfNames }}
      - {{ $pf }}
      {{ end }}
    {{ end }}
    {{ if not (eq (len $e.NicSelector.RootDevices) 0) }}
    rootDevices:
      {{ range $k, $rd := $e.NicSelector.RootDevices }}
      - "{{ $rd }}"
      {{ end }}
    {{ end }}
    vendor: {{ $e.NicSelector.Vendor }}
    deviceId: {{ $e.NicSelector.DeviceId }}
  nodeSelector:
    node-role.kubernetes.io/{{ $workerOspRole }}: ""
  numVfs: {{ $e.NumVfs }}
  priority: 5
  resourceName: sriovnic_{{ $workerOspRoleFormatted }}_{{ $e.Interface }}
  {{ end }}
{{ end }}